ro.axonsoft.internship172:
  reference-date: 2017-07-22
  mode: db
  #mode: file
  input-file: input.csv
  output-file: output.dat
  ro-id-card-series-map:
    CJ:
      - KX
      - CJ
    B:
      - DP
      - DR
      - DT
      - RD
      - RR
      - RT
      - RX
    MM:
      - MM
    NT:
      - NT
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.axonsoft.local:3306/internship_learn
    username: internship_learn
    password: internship_learn
    initialize: false
    tomcat:
      max-active: 5
      max-wait: 10000
      test-on-borrow: true
  thymeleaf.cache: false